In [10]:
import numpy as np

In [11]:
# create from list
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5,"peime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape )
arr2D= np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr2D,arr2D.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'peime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [20]:
# create
arr1 = np.zeros((2,3), dtype="int64") #prefill with zeroes
print(arr1, arr1.shape)

arr2 = np.ones((5, )) #prefill with one
print(arr2, arr2.shape)

arr3 = np.full((3,4), 100) #prefill with values
print(arr3, arr3.shape)

arr4= np.eye(3) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0,11,2) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,4) #evenly spaced array
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [21]:
#propertiees

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64
