In [1]:
import numpy as np



In [4]:
#operations on arrays

arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape(3,2)
print(reshaped, reshaped.shape)

flattened = arr.flatten() #2D>1D
print(flattened, flattened.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [5]:
#indexing 
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr[0])
print(arr[3])
print(arr2[0][2])




1
4
3


In [7]:
#fancy indexing

arr = np.array([1,2,3,4,5])

idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [10]:
#boolean indexing

arr = np.array([1,2,3,4,5,])

print(arr[arr > 3])
print(arr[arr%2==0])
print(arr[arr%2!=0])

[4 5]
[2 4]
[1 3 5]


In [11]:
#slicing

arr= np.array([1,2,3,4,5])

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [15]:
 # python lib vs numpy
# lib makes copy but numpy makes view(original)

nums = [1,2,3,4,5] 
sub_list = nums[1:3]
print(sub_list)

sub_list[0] = 200
print(sub_list)
print(nums)


arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [16]:
# to make copy from the array using numpy

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3].copy() #no change will reflect in array
print(sub_arr)

sub_arr[0] = 200
print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]
