In [2]:
import numpy as np

In [4]:
# vectorization

arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr**2)
print(arr + 10)
print(arr + arr2)


[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [5]:
#broaadcasting

arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])

print(arr.shape)
print(arr2.shape)

print(arr + arr2)





(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [7]:
# normalization

arr= np.array([[1,2], [3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalised_arr = (arr-mean)/std_dev
print(normalised_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [10]:

# mathmatical functions

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
